# Site settings
title: Conor MacBride
tagline: Senior Data Scientist
email: conor@macbride.me
profile_picture: conor.jpeg
description: >-
  Senior Data Scientist at Allstate NI specialising in AI, NLP, and generative AI,
  with a background in physics and open-source development.
url: "https://macbride.me" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: conormacbride
github_username: ConorMacBride
gh: <i class="fab fa-github" aria-hidden="true"></i>
social:
  name: Conor MacBride
  links:
    - https://www.linkedin.com/in/conormacbride/
    - https://github.com/ConorMacBride
twitter:
  card: summary_large_image
logo: /assets/images/conor.jpeg
locale: en_GB
images: /assets/images

# Build settings
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-seo-tag
  - liquid_reading_time

collections:
  - experience
  - education
  - volunteering
  - publications
  - talks

defaults:
  -
    scope:
      path: ""
      type: education
    values:
      noexpand: true
      mobcollapse: false
      homepage: false
  -
    scope:
      path: ""
      type: publications
    values:
      noexpand: true
      mobcollapse: false
  -
    scope:
      path: ""
      type: talks
    values:
      noexpand: true
      mobcollapse: false
  -
    scope:
      path: ""
      type: posts
    values:
      author: Conor MacBride
  -
    scope:
      path: ""
    values:
      subentry: false
      link: false
      mobcollapse: true
      image: /assets/images/default-card.png
      mathjax: false
      homepage: false
